### ISSUE TITLE
Create Post

### ISSUE THREAD

**Issue by mjohn365** [acmadden/YourCampusNeeds#11]
As a user I would like to create a post so that I can offer my goods/services to others users. The users can create posts visible to other users. The user should be prompted to enter various details about the item.

**Comment by acmadden** [comment]
Just thought of this. I was getting an unhandled  unsubscription using the modal. That means i something in the create post component was releasing to early, ngOnDestroy? 

After I fix that I should be able to inject the component directly into the modal.

**Comment by acmadden** [comment]
Yup I was right to an extent. Needed to create a subscription reference and then unsubscribe in OnDestroy().
